### ISSUE TITLE
There is no documentation for how to build the project

### ISSUE THREAD

**Issue by gabrielsr** [lesunb/CRGMToPRISM#2]

**Comment by gabrielsr** [comment]
working in it! Need to study about how to develop a plugin. Any help on it @danilomendonca ?

**Comment by danilomendonca** [comment]
Gabriel, cole aqui o erro na dependência para que eu veja assim que possível.

**Comment by gabrielsr** [comment]
Fazendo o build pelo maven:

[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Error resolving version for 'org.antlr:antlr4-maven-plugin': Plugin requires Maven version 3.0


Já importando como plugin Eclipse não obtenho um erro. Mas não consigo ver o menu para gerar o código. Não sei se estou esquecendo de fazer algo...

**Comment by gabrielsr** [comment]
Meu maven estava desatualizado. Atualizei para o 3.0.4. Obtive um erro de versão do código do java. Setei no pom para uma versão mais recente do Java e consegui fazer o build do jar.

**Comment by danilomendonca** [comment]
Eu corrigi esse erro em meu ambiente instalando a versão 3.0 do maven no linux. Dá uma googleada que você acha.

**Comment by danilomendonca** [comment]
Ótimo!

**Comment by gabrielsr** [comment]
Não é possível importar o jar gerado pelo maven como plugin no eclipse. Vendo se existe algum plugin maven.

**Comment by gabrielsr** [comment]
Explorei um pouco sobre o plugin maven tycho (https://eclipse.org/tycho/documentation.php) mas vi que o factory teria que ser muito grande. 
Já tentando importar como projeto eclipse,  falta a dependência  taom4e-platform;bundle-version="1.0.0" declarada em META-INF/MANIFEST.MF

**Comment by gabrielsr** [comment]
alguma idéia @danilomendonca ?

**Comment by gabrielsr** [comment]
Acho que encontrei a versão correta do taom4e e fiz um pull request. Pode ver se ficou certo?

* Algumas classes apresentam erro porque possuem @Override em métodos, mas não sobreescrevem na verdade.  É um erro do código ou do meu ambiente que ainda está zoado?

** Ainda não consegui ver o menu para gerar código PRISM. Em que situação ele deveria aparecer?

**Comment by danilomendonca** [comment]
The project uses both eclipse plugin dependencies and maven. Any dependency not included as an eclipse plugin (plugin.xml -> dependencies) should be added as a maven dependency/plugin.
